#!/bin/sh

#PBS -l nodes=8:ppn=32,walltime=00:05:00
#PBS -N MPI_P1_8
#PBS -M mpati008@ucr.edu
#PBS -m abe

module load gcc-4.6.2
module load mvapich2-1.9a2/gnu-4.6.2

PBS_O_WORKDIR=/home/mpati008/hpc3

cd $PBS_O_WORKDIR

mpirun ./mpi_part1 10000000000 8 >> results.txt
