#!/bin/sh
#PBS -l nodes=2:ppn=32,walltime=00:05:00
#PBS -N MPI_P3_2
#PBS -M mpati008@ucr.edu
#PBS -m abe

module load gcc-4.6.2
module load mvapich2-1.9a2/gnu-4.6.2

PBS_O_WORKDIR=/home/kaimo901/test/mpati008

cd $PBS_O_WORKDIR

mpirun ./mpi_part3 10000000000 2 >> results.txt

